export const twitterSpaceTopics = [
  'Cryptocurrency',
  'Stock Market',
  'NFTs',
  'Entrepreneurship',
  'Personal Finance',
  'Investing',
  'World News',
  'Premier League',
  'Bitcoin cryptocurrency',
  'Digital creators',
  'US national news',
  'Mindful',
  'Financial Planning',
  'Venture Capital',
  'Real Estate',
  'Tax Strategies',
  'Retirement Planning',
  'Hip Hop',
  'K-Pop',
  'Classical Music',
  'Music Production',
  'Jazz',
  'Rock Music',
  'Electronic Music',
  'Music Theory',
  'Live Concerts',
  'Songwriting',
  'Football',
  'Basketball',
  'Esports',
  'Fitness',
  'Soccer',
  'Baseball',
  'Tennis',
  'Golf',
  'Running',
  'Yoga',
  'Artificial Intelligence',
  'Blockchain',
  'Cybersecurity',
  'Gadgets',
  'Software Development',
  'Cloud Computing',
  'Data Science',
  'Internet of Things',
  'Web Development',
  'Tech Startups',
  'Mobile Gaming',
  'Sociology',
  'PC Gaming',
  'Game Development',
  'Streaming',
  'Virtual Reality',
  'Console Gaming',
  'Game Design',
  'Indie Games',
  'Reality TV',
  'Gaming Culture',
  'Politics',
  'Climate Change',
  'International Relations',
  'Breaking News',
  'Elections',
  'Human Rights',
  'Geopolitics',
  'Economic Policy',
  'Social Justice',
  'Health News',
  'Movies',
  'TV Shows',
  'Celebrity Gossip',
  'Comedy',
  'Anime',
  'Documentaries',
  'Film Production',
  'Streaming Platforms',
  'Theater',
  'Pop Culture',
  'Visual Arts',
  'Literature',
  'Fashion',
  'Photography',
  'Dance',
  'Sculpture',
  'Graphic Design',
  'Poetry',
  'Architecture',
  'Art History',
  'Parenting',
  'Home Decor',
  'Cooking',
  'Pet Care',
  'Gardening',
  'DIY Projects',
  'Family Activities',
  'Home Organization',
  'Sustainable Living',
  'Child Development',
  'Job Search',
  'Career Development',
  'Remote Work',
  'Freelancing',
  'Leadership',
  'Resume Writing',
  'Work-Life Balance',
  'Professional Networking',
  'Career Transitions',
  'Entrepreneurial Skills',
];
